--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2
projects:
  MagicWE2:
    path: ""
    icon: "resources/magicwe_icon_square_small.png"
    excludeFiles:
      - "resources/magicwe_icon_square.png"
      - "resources/magicwe_icon_square_small.png"
      - "resources/magicwe_icon_wide.png"
    lint:
      phpstan: false
    libs:
      - src: BlockHorizons/libschematic/libschematic
        version: ^2.0.1
      - src: thebigsmilexd/customui/customui
        version: ^4.0.0
        branch: PM4
      - src: thebigsmilexd/apibossbar/apibossbar
        version: ^0.1.4
        branch: PM4
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: muqsit/invmenu/InvMenu
        version: ^4.1.0
        branch: "4.0"
      - src: thebigsmilexd/libstructure/libstructure
        version: ^0.1.4
        branch: mcstructure
      - src: buchwasa/ScoreFactory/ScoreFactory
        version: ^3.0.1
        branch: pm4
...
