--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2
projects:
  MagicWE2:
    path: ""
    icon: "resources/magicwe_icon_square_small.png"
    excludeFiles:
      - "resources/magicwe_icon_square.png"
      - "resources/magicwe_icon_square_small.png"
      - "resources/magicwe_icon_wide.png"
    lint:
      phpstan: false
    libs:
      - src: BlockHorizons/libschematic/libschematic
        version: ^2.0.1
      - src: WolvesFortress/FormAPI/libFormAPI
        version: ^1.3.0
        branch: pm4
      - src: thebigsmilexd/apibossbar/apibossbar
        version: ^0.1.5
        branch: PM4
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: muqsit/invmenu/InvMenu
        version: ^4.3.4
        branch: "4.0"
      - src: thebigsmilexd/libstructure/libstructure
        version: ^0.1.7
        branch: libblockstate
      - src: thebigsmilexd/libblockstate/libblockstate
        version: ^0.0.1
        branch: master
      - src: Ifera/scorefactory/ScoreFactory
        version: ^3.1.0
        branch: master
...
