<?php

declare(strict_types=1);

namespace xenialdan\MagicWE2\commands;

use pocketmine\command\CommandSender;
use pocketmine\command\PluginCommand;
use pocketmine\Player;
use pocketmine\plugin\Plugin;
use pocketmine\utils\TextFormat;
use xenialdan\MagicWE2\API;
use xenialdan\MagicWE2\Loader;

class FillCommand extends PluginCommand{
	public function __construct(Plugin $plugin){
		parent::__construct("/set", $plugin);
		$this->setAliases(["/fill"]);
		$this->setPermission("we.command.set");
		$this->setDescription("Fill an area");
	}

	public function getUsage(): string{
		return parent::getUsage(); // TODO: Change the autogenerated stub
	}

	public function execute(CommandSender $sender, string $commandLabel, array $args){
		/** @var Player $sender */
		$return = true;
		try{
			$messages = [];
			$error = false;
			$newblocks = API::blockParser(array_shift($args), $messages, $error);
			foreach ($messages as $message){
				$sender->sendMessage($message);
			}
			$return = !$error;
			if ($return){
				$sender->sendMessage(API::fill(($session = API::getSession($sender))->getLatestSelection(), $sender->getLevel(), $newblocks, ...$args));
			} else{
				throw new \TypeError("Could not fill with the selected blocks");
			}
		} catch (\Error $error){
			$sender->sendMessage(Loader::$prefix . TextFormat::RED . "Looks like you are missing an argument or used the command wrong!");
			$sender->sendMessage(Loader::$prefix . TextFormat::RED . $error->getMessage());
			$return = false;
		} finally{
			return parent::execute($sender, $commandLabel, $args) && $return;
		}
	}
}
