<?php

declare(strict_types=1);

namespace xenialdan\MagicWE2\commands;

use pocketmine\command\CommandSender;
use pocketmine\command\PluginCommand;
use pocketmine\Player;
use pocketmine\plugin\Plugin;
use pocketmine\utils\TextFormat;
use xenialdan\MagicWE2\API;
use xenialdan\MagicWE2\Loader;

class ReplaceCommand extends PluginCommand{
	public function __construct(Plugin $plugin){
		parent::__construct("/replace", $plugin);
		$this->setPermission("we.command.replace");
		$this->setDescription("Replace blocks in an area");
	}

	public function getUsage(): string{
		return parent::getUsage(); // TODO: Change the autogenerated stub
	}

	public function execute(CommandSender $sender, string $commandLabel, array $args){
		/** @var Player $sender */
		$return = true;
		try{
			$messages = [];
			$error = false;
			$blocks1 = API::blockParser(array_shift($args), $messages, $error);
			$blocks2 = API::blockParser(array_shift($args), $messages, $error);
			foreach ($messages as $message){
				$sender->sendMessage($message);
			}
			$return = !$error;
			if ($return){
				$sender->sendMessage(API::replace(Loader::$selections[$sender->getLowerCaseName()], $sender->getLevel(), $blocks1, $blocks2, ...$args));
			} else{
				throw new \TypeError("Could not replace with the selected blocks");
			}
		} catch (\TypeError $error){
			$sender->sendMessage(Loader::$prefix . TextFormat::RED . "Looks like you are missing an argument or used the command wrong!");
			$sender->sendMessage(Loader::$prefix . TextFormat::RED . $error->getMessage());
			$return = false;
		} finally{
			return $return;
		}
	}
}
