<?php

declare(strict_types=1);

namespace xenialdan\MagicWE2\commands;

use pocketmine\command\CommandSender;
use pocketmine\command\PluginCommand;
use pocketmine\item\enchantment\Enchantment;
use pocketmine\item\ItemFactory;
use pocketmine\item\ItemIds;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\Player;
use pocketmine\plugin\Plugin;
use pocketmine\utils\TextFormat;
use xenialdan\MagicWE2\Loader;
use xenialdan\MagicWE2\WEException;

class WECommand extends PluginCommand{
	public function testPermissionSilent(CommandSender $target): bool{
		return false;
	}

	public function getDefaultCommandData(): array{
		return parent::getDefaultCommandData(); // TODO: Change the autogenerated stub
	}
}
